version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7-fpm-alpine
    volumes:
      - ./www:/code